require: rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'

Style/ExpandPathArguments:
  Enabled: false

Style/Encoding:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
